#pragma once
#include <string_view>

namespace xenon::ui {
enum class Language { english, simplified_chinese };
// The active language stays fixed for this process, matching CEF's startup locale.
inline Language language=Language::english;
inline Language preferred_language=Language::english;
inline const char* language_tag(Language value) {return value==Language::simplified_chinese?"zh-CN":"en-US";}
struct Translation {const wchar_t* english;const wchar_t* chinese;};
inline constexpr Translation translations[]{
  {L"Quick tour",L"快速导览"},{L"GitHub documentation",L"GitHub 使用文档"},
  {L"Back",L"后退"},{L"Forward",L"前进"},{L"Reload",L"刷新"},{L"Stop",L"停止"},
  {L"Go to address",L"打开地址"},{L"Controls",L"控制中心"},{L"Menu",L"菜单"},
  {L"New tab",L"新标签页"},{L"Previous match",L"上一个匹配"},{L"Next match",L"下一个匹配"},{L"Close find",L"关闭查找"},
  {L"Workspace tabs",L"工作区标签页"},{L"Opening",L"正在打开"},{L"You",L"您"},{L"No agent",L"无代理"},
  {L"Agent",L"代理"},{L"Workspace",L"工作区"},{L"Personal",L"个人"},
  {L" · Paused for you",L" · 已暂停，等待您操作"},{L" · Handing off",L" · 正在移交"},
  {L" · Agent control",L" · 代理控制"},{L" · Unavailable",L" · 不可用"},{L" · Protected authentication",L" · 登录保护中"},
  {L"Xenon Browser",L"Xenon 浏览器"},{L"Xenon / Workspaces",L"Xenon / 工作区"},
  {L"Find on page\tCtrl+F",L"在页面中查找\tCtrl+F"},{L"Zoom in\tCtrl++",L"放大\tCtrl++"},
  {L"Zoom out\tCtrl+-",L"缩小\tCtrl+-"},{L"Reset zoom\tCtrl+0",L"重置缩放\tCtrl+0"},
  {L"Bookmark this page\tCtrl+D",L"将此页加入书签\tCtrl+D"},{L"Bookmarks",L"书签"},{L"History",L"历史记录"},{L"Downloads",L"下载"},
  {L"Print\tCtrl+P",L"打印\tCtrl+P"},{L"Save as PDF…",L"另存为 PDF…"},{L"Site permissions",L"网站权限"},
  {L"New private workspace",L"新建隐私工作区"},{L"Close tab\tCtrl+W",L"关闭标签页\tCtrl+W"},
  {L"Theme: System",L"主题：跟随系统"},{L"Theme: Light",L"主题：浅色"},{L"Theme: Dark",L"主题：深色"},
  {L"Narrower",L"缩窄"},{L"Wider",L"加宽"},{L"Reset width",L"重置宽度"},{L"Sidebar width",L"侧边栏宽度"},
  {L"Check for updates",L"检查更新"},{L"About Xenon",L"关于 Xenon"},{L"Third-party notices",L"第三方声明"},{L"Exit Xenon",L"退出 Xenon"},
  {L"Sidebar resized for this run; saving failed.",L"侧边栏宽度已更改，但无法保存。"},
  {L"Browser history could not be saved.",L"无法保存浏览历史记录。"},
  {L"Browser metadata could not be saved. Existing data is preserved.",L"无法保存浏览器信息。现有数据已保留。"},
  {L"This address could not be opened.",L"无法打开此地址。"},
  {L"Bookmark saved.",L"书签已保存。"},{L"Bookmark could not be saved.",L"无法保存书签。"},
  {L"PDF saved.",L"PDF 已保存。"},{L"PDF could not be saved.",L"无法保存 PDF。"},
  {L"Theme changed for this run; saving failed.",L"主题已更改，但无法保存。"},
  {L"Theme saved. Web pages use it after Xenon restarts.",L"主题已保存。重启 Xenon 后网页将使用此主题。"},
  {L"The browser action could not be completed. Existing data is preserved.",L"无法完成浏览器操作。现有数据已保留。"},
  {L"Restart Xenon to apply the selected language. Save unfinished website work before exiting.",L"重启 Xenon 后将应用所选语言。退出前请保存尚未完成的网页工作。"},
  {L"The language preference could not be saved. Try again.",L"无法保存语言设置。请重试。"},
  {L"Language preference saved.",L"语言设置已保存。"},
  {L"Website permission request",L"网站权限请求"},{L"Xenon Bookmarks",L"Xenon 书签"},{L"Xenon History",L"Xenon 历史记录"},
  {L"Xenon Downloads",L"Xenon 下载"},{L"Xenon Site Permissions",L"Xenon 网站权限"},{L"Xenon Third-party Notices",L"Xenon 第三方声明"},
  {L"Allow",L"允许"},{L"Deny",L"拒绝"},{L"Reset site permissions",L"重置网站权限"},{L"Open selected",L"打开所选项"},
  {L"Remove bookmark",L"删除书签"},{L"Close",L"关闭"},{L"Name",L"名称"},{L"Title",L"标题"},{L"Status / bytes",L"状态 / 字节数"},
  {L"Complete",L"已完成"},{L"Canceled",L"已取消"},{L"Downloading",L"正在下载"},{L" bytes",L" 字节"},{L"Workspace: ",L"工作区："},
  {L"Xenon Browser\n",L"Xenon 浏览器\n"},
  {L"\n\nA local browser for people and MCP agents.\nCEF supplies the sandboxed web engine.\n\nThird-party licenses and notices are available from the Menu.",L"\n\n供用户和 MCP 代理使用的本地浏览器。\nCEF 提供沙盒网页引擎。\n\n可从菜单查看第三方许可证和声明。"},
  {L"Open engine credits",L"打开引擎致谢"},{L"Site: ",L"网站："},
  {L"\n\nCamera, microphone, location and notification requests use native approval prompts.\nReset clears remembered permissions for this HTTPS origin.\nBrowser and workspace permissions are configured in Controls.",L"\n\n摄像头、麦克风、位置和通知请求通过原生提示征求许可。\n重置会清除此 HTTPS 来源已保存的权限。\n浏览器和工作区权限可在控制中心配置。"},
  {L"Remembered site permissions reset.",L"已重置保存的网站权限。"},{L"Site permissions could not be reset.",L"无法重置网站权限。"},
  {L"Agent pointer",L"代理指针"},{L"Web page",L"网页"},
  {L"Website: ",L"网站："},
  {L"\n\nRequested access: ",L"\n\n请求的权限："},
  {L"\n\nAllow only if you intended to give this website access.",L"\n\n仅在您确实希望授予此网站相应权限时选择允许。"},
  {L"Location",L"位置"},{L"Notifications",L"通知"},{L"Camera",L"摄像头"},{L"Microphone",L"麦克风"},{L"Clipboard",L"剪贴板"},{L"Storage access",L"存储访问"},
  {L"Media access",L"媒体访问"},{L"Camera and microphone",L"摄像头和麦克风"},{L"Media access: microphone",L"媒体访问：麦克风"},
  {L"Xenon Controls",L"Xenon 控制中心"},{L"Clients",L"客户端"},{L"Workspaces",L"工作区"},{L"Passwords",L"密码"},
  {L"Create workspace",L"创建工作区"},{L"Configure workspace",L"配置工作区"},{L"Configure client",L"配置客户端"},
  {L"Workspace name",L"工作区名称"},{L"Client",L"客户端"},{L"Save",L"保存"},
  {L"A blank tab will open with human ownership.",L"将打开一个由您控制的空白标签页。"},
  {L"Changes take effect when you choose Save. Unchecked capabilities are read-only.",L"选择保存后更改生效。未勾选的功能仅允许读取。"},
  {L"Paired clients",L"已配对客户端"},
  {L"Interact with pages and create tabs",L"操作网页并创建标签页"},{L"Upload approved files",L"上传已获准的文件"},
  {L"Download files",L"下载文件"},{L"Use permitted saved accounts",L"使用已获准的保存账号"},
  {L"Allow this client in this workspace",L"允许此客户端访问该工作区"},{L"Allow automatic workspace creation",L"允许自动创建工作区"},
  {L"Inherit client files",L"继承客户端文件权限"},{L"Inherit client accounts",L"继承客户端账号权限"},
  {L"Restrict files to checked items",L"仅允许勾选的文件"},{L"Restrict accounts to checked items",L"仅允许勾选的账号"},
  {L"Concurrent workers",L"并发代理数"},{L"Automatic workspaces",L"自动工作区数"},
  {L"Available resources · checked items form restrictions when enabled",L"可用资源 · 启用限制时仅允许勾选项"},
  {L"Resources · check saved accounts to grant them to this client",L"资源 · 勾选保存的账号以授权此客户端"},
  {L"Name / HTTPS origin",L"名称 / HTTPS 来源"},{L"Type",L"类型"},
  {L"Grant file",L"授权文件"},{L"Grant folder",L"授权文件夹"},{L"Revoke selected",L"撤销所选授权"},
  {L"Folder",L"文件夹"},{L"File",L"文件"},{L"Account",L"账号"},
  {L"Select an item to configure.",L"请先选择要配置的项目。"},
  {L"Saved. Effective permissions also depend on the client's overall policy.",L"已保存。实际权限还取决于客户端的总体策略。"},
  {L"Could not save all changes. Review permissions and retry.",L"无法保存全部更改。请检查权限后重试。"},
  {L"This resource could not be granted.",L"无法授权此资源。"},
  {L"Enter a workspace name with at most 80 characters and no control characters.",L"请输入不超过 80 个字符且不含控制字符的工作区名称。"},
  {L"Enter numeric quotas.",L"请输入数字配额。"},
  {L"Xenon Updates",L"Xenon 更新"},{L"Xenon  /  Updates",L"Xenon  /  更新"},{L"Automatic checks are off",L"自动检查已关闭"},
  {L"Current version: ",L"当前版本："},
  {L"Available version: ",L"可用版本："},{L"Available version: —",L"可用版本：—"},
  {L"Downloaded ",L"已下载 "},{L" of ",L" / "},
  {L"Unsigned alpha software. Downloading does not install it. Install and exit asks for confirmation, then closes Xenon before opening setup.",L"这是未签名的 alpha 软件。下载不会自动安装。安装并退出会征求确认，然后关闭 Xenon 并打开安装程序。"},
  {L"Setup upgrades or installs Xenon for your Windows account. Portable users should launch the installed copy from the Start menu afterward.",L"安装程序为您的 Windows 账号安装或升级 Xenon。便携版用户随后应从开始菜单启动已安装的版本。"},
  {L"Check again",L"再次检查"},{L"Download update",L"下载更新"},{L"Install and exit",L"安装并退出"},{L"Cancel",L"取消"},
  {L"The updates window could not open.",L"无法打开更新窗口。"},
  {L"Check for a newer Xenon release when you are ready.",L"准备好后可检查 Xenon 的新版本。"},
  {L"Canceled. No update was installed.",L"已取消。未安装任何更新。"},
  {L"The update operation could not be completed.",L"无法完成更新操作。"},
  {L"Updates could not start. Try again later.",L"无法开始更新。请稍后重试。"},
  {L"Checking for a newer release…",L"正在检查新版本…"},
  {L"Update check canceled.",L"已取消检查更新。"},{L"A newer Xenon release is available.",L"有可用的 Xenon 新版本。"},
  {L"No newer release is available for this version.",L"此版本目前没有可用更新。"},
  {L"Downloading the update installer…",L"正在下载更新安装程序…"},
  {L"Download canceled. No update was installed.",L"下载已取消。未安装任何更新。"},
  {L"Installer downloaded and verified. Choose Install update when ready.",L"安装程序已下载并通过验证。准备好后可选择安装更新。"},
  {L"Update installation is unavailable in this window.",L"此窗口无法安装更新。"},
  {L"Install the update and exit Xenon?\n\nSave unfinished website work first. Xenon will close its tabs normally and disconnect agents, then open the verified unsigned setup program. Other Xenon instances must also be closed before installation.\n\nSetup upgrades your installed copy in its existing folder. Your saved workspaces and accounts are retained. When setup finishes, open Xenon from the Start menu.",L"安装更新并退出 Xenon？\n\n请先保存尚未完成的网页工作。Xenon 将正常关闭标签页并断开代理连接，然后打开已验证但未签名的安装程序。安装前还必须关闭其他 Xenon 实例。\n\n安装程序将在现有文件夹中升级已安装的版本。保存的工作区和账号将保留。安装完成后，请从开始菜单打开 Xenon。"},
  {L"Install Xenon update",L"安装 Xenon 更新"},
  {L"Rechecking the installer before exiting Xenon…",L"正在退出 Xenon 前重新验证安装程序…"},
  {L"Installer verified. Closing Xenon before starting setup…",L"安装程序已通过验证。正在关闭 Xenon 以启动安装…"},
  {L"Canceling the current update operation…",L"正在取消当前更新操作…"},
  {L"Select the login tab before filling a saved account.",L"填入保存的账号前，请先选择登录标签页。"},
  {L"Unlock Windows before using saved accounts.",L"使用保存的账号前，请先解锁 Windows。"},
  {L"The selected login tab is still being checked…",L"仍在检查所选登录标签页…"},
  {L"A saved-account fill is already in progress.",L"正在填入保存的账号。"},
  {L"Checking the selected tab for a supported HTTPS login form…",L"正在检查所选标签页中支持的 HTTPS 登录表单…"},
  {L"That login page changed. Open saved accounts again on the current login form.",L"登录页面已更改。请在当前登录表单上重新打开保存的账号。"},
  {L"Choose a saved account first.",L"请先选择保存的账号。"},
  {L"Filling the selected account…",L"正在填入所选账号…"},
  {L"Filling could not be confirmed. Check the login page before trying again.",L"无法确认填写结果。请检查登录页面后再重试。"},
  {L"Fill saved account",L"填入保存的账号"},{L"Xenon  /  Saved accounts",L"Xenon  /  保存的账号"},
  {L"Choose an account for this login website",L"选择用于此登录网站的账号"},{L"Saved account",L"保存的账号"},
  {L"Fills this form without submitting. You finish signing in. Agent observations stay protected during login.",L"填写表单但不提交。请由您完成登录。登录期间代理观察将保持受保护状态。"},
  {L"Fill",L"填入"},{L"Not now",L"暂不"},
  {L"Saved-account fill is unavailable for this tab. Use an HTTPS login form with an account saved for this exact website.",L"此标签页无法填入保存的账号。请使用 HTTPS 登录表单，并确保账号保存的网站来源与当前网站完全一致。"},
  {L"Saved username filled. Continue on the website, then use Fill saved account again at the password step.",L"已填入保存的用户名。请在网站上继续，到密码步骤时再次选择填入保存的账号。"},
  {L"Saved password filled without submitting. Return to the login tab to continue signing in.",L"已填入保存的密码，但未提交。请返回登录标签页继续登录。"},
  {L"Saved account filled without submitting. Return to the login tab to continue signing in.",L"已填入保存的账号，但未提交。请返回登录标签页继续登录。"},
  {L"Saved-account filling is temporarily unavailable.",L"暂时无法填入保存的账号。"},
  {L"Saved password updated in Xenon.",L"已在 Xenon 中更新保存的密码。"},{L"Password saved in Xenon.",L"密码已保存到 Xenon。"},
  {L"This login could not be saved. Close this prompt and try the login again.",L"无法保存此次登录。请关闭提示后重新登录。"},
  {L"The login could not be saved. No password details were displayed or logged.",L"无法保存登录信息。未显示或记录任何密码详情。"},
  {L"Update saved password?",L"更新保存的密码？"},{L"Save password in Xenon?",L"将密码保存到 Xenon？"},
  {L"Update with the password you just submitted?",L"使用刚提交的密码更新？"},{L"Save the password you just submitted?",L"保存刚提交的密码？"},
  {L"Login website — this account will be saved for this origin",L"登录网站 — 此账号将保存用于该来源"},
  {L"Account: ",L"账号："},
  {L"Sign-in may still require verification. Save only if this password is correct. Saving does not grant agent access.",L"登录可能仍需验证。仅在确认密码正确时保存。保存不会授予代理访问权限。"},
  {L"Update",L"更新"},{L"Done.",L"已完成。"},
  {L"Paused for human",L"已暂停，等待用户"},{L"Protected authentication",L"登录保护中"},{L"Website dialog",L"网站对话框"},
  {L"Human control",L"用户控制"},{L"Agent control",L"代理控制"},{L"Agent unavailable",L"代理不可用"},{L"No owner",L"无控制者"},{L"Agent ",L"代理 "},
  {L" (paused for you)",L"（已暂停，等待您）"},{L"NOT SAVED — retry revocation: ",L"未保存 — 请重试撤销："},
  {L" · Connected",L" · 已连接"},{L" · Offline",L" · 离线"},{L"Interactive",L"可交互"},{L"Read-only",L"只读"},
  {L" (retiring)",L"（正在停用）"},{L" (offline)",L"（离线）"},
  {L"No website dialog waiting.",L"没有待处理的网站对话框。"},
  {L"Some controls are unavailable while the vault is locked.",L"密码库锁定时部分控件不可用。"},
  {L"Selected file or folder grant revoked.",L"已撤销所选文件或文件夹的授权。"},
  {L"The file permission could not be changed.",L"无法更改文件权限。"},
  {L"Private workspaces are human-only and do not accept agent file grants.",L"隐私工作区仅供用户使用，不接受代理文件授权。"},
  {L"Select a workspace first.",L"请先选择工作区。"},
  {L"Xenon File Permissions",L"Xenon 文件权限"},{L"Xenon File Permissions — ",L"Xenon 文件权限 — "},
  {L"Xenon  /  File permissions",L"Xenon  /  文件权限"},
  {L"Approved resources remain subject to client and workspace permissions.",L"已授权资源仍受客户端和工作区权限约束。"},
  {L"Private workspace removed. Saved passwords and downloaded files were kept.",L"已删除隐私工作区。保存的密码和下载的文件已保留。"},
  {L"Workspace removed. Its site data will be deleted on the next launch; locked files are retried later. Saved passwords and downloaded files were kept.",L"工作区已删除。网站数据将在下次启动时删除，锁定的文件会在之后重试。保存的密码和下载的文件已保留。"},
  {L"Select the workspace to remove.",L"请选择要删除的工作区。"},
  {L"Personal is the default workspace and cannot be removed. Other workspaces can be removed here.",L"个人是默认工作区，不能删除。可在此删除其他工作区。"},
  {L"Workspace removal is already in progress. Finish any held input or answer its pending website dialog.",L"正在删除工作区。请结束按住的输入或回应待处理的网站对话框。"},
  {L"Remove ",L"删除 "},
  {L"?\n\nThis closes all its tabs, stops its agents and downloads, and removes its agent and file permissions. Unsaved work in those tabs will be lost.\n\n",L"？\n\n这会关闭其全部标签页、停止代理和下载，并移除代理和文件权限。标签页中未保存的工作将丢失。\n\n"},
  {L"Its private browsing session will be discarded.",L"其隐私浏览会话将被丢弃。"},
  {L"Its cookies, sign-in sessions, history and other profile data will be deleted on the next launch. Files that are still locked will be retried on later launches.",L"其 Cookie、登录会话、历史记录和其他配置数据将在下次启动时删除。仍被锁定的文件将在之后启动时重试。"},
  {L"\n\nSaved passwords in the shared vault, downloaded files and files from approved folders will be kept. Tabs and stored data in other workspaces are kept.",L"\n\n共享密码库中的密码、下载的文件及已授权文件夹中的文件将保留。其他工作区的标签页和存储数据也将保留。"},
  {L"Remove workspace",L"删除工作区"},
  {L"Removing workspace. Waiting for active input to finish before closing its tabs…",L"正在删除工作区。等待当前输入结束后关闭其标签页…"},
  {L"Client paired with read-only permissions. Configure it and share a workspace to allow access.",L"客户端已配对，权限为只读。请配置客户端并共享工作区以允许访问。"},
  {L"Client access revoked and saved. Its queued actions were canceled.",L"已撤销客户端访问并保存。排队的操作已取消。"},
  {L"Client blocked for this run, but revocation could not be saved. Restarting can restore access. Select its NOT SAVED row and click Revoke / retry.",L"本次运行已阻止该客户端，但无法保存撤销设置。重启可能恢复其访问。请选择未保存的条目并点击撤销 / 重试。"},
  {L"Select a paired client or an unsaved revocation to retry.",L"请选择已配对的客户端或未保存的撤销条目以重试。"},
  {L"Workspace shared with the selected client.",L"已与所选客户端共享工作区。"},{L"Select a client and workspace.",L"请选择客户端和工作区。"},
  {L"Ownership requested for you until explicitly given to an agent. Current input will finish.",L"已请求由您控制，直到您明确交给代理。当前输入将先完成。"},
  {L"Control offered to the selected connected agent in this workspace.",L"已向此工作区中所选的已连接代理提供控制权。"},
  {L"All agent control stopped. Restart Xenon to accept clients again.",L"已停止所有代理控制。重启 Xenon 后可重新接受客户端。"},
  {L"Resume agent observations for this tab? Confirm that login is finished and no password, code, recovery key, or other secret is visible.",L"恢复代理对此标签页的观察？请确认登录已完成，且没有可见的密码、验证码、恢复密钥或其他秘密。"},
  {L"Resume observations",L"恢复观察"},{L"Protected authentication ended for the selected tab.",L"已结束所选标签页的登录保护。"},
  {L"Selected tab's script dialog answered.",L"已回应所选标签页的脚本对话框。"},
  {L"Review this local password import. Usernames and passwords are masked.\n\nValid rows: ",L"请检查此次本地密码导入。用户名和密码已隐藏。\n\n有效行数："},
  {L"\nInvalid rows to skip: ",L"\n将跳过的无效行数："},{L"\nDuplicate/existing rows: ",L"\n重复 / 已有行数："},{L"\nConflicting rows: ",L"\n冲突行数："},
  {L"Additional accounts are included in the counts above.\n",L"其他账号已包含在上述统计中。\n"},
  {L"The CSV contains no supported HTTPS logins. Nothing was imported.",L"CSV 中没有支持的 HTTPS 登录信息。未导入任何内容。"},
  {L"\nImport these logins? The source CSV remains unencrypted on disk until you remove it.",L"\n导入这些登录信息？源 CSV 会以未加密形式保留在磁盘上，直到您将其删除。"},
  {L"Preview password import",L"预览密码导入"},{L"Import canceled. Nothing was imported.",L"导入已取消。未导入任何内容。"},
  {L"Some accounts have different passwords in the CSV.\n\nYes: replace conflicting saved passwords with the CSV values.\nNo: keep existing passwords and skip conflicting rows.\nCancel: import nothing.",L"CSV 中部分账号的密码与保存的密码不同。\n\n是：用 CSV 中的值替换冲突的密码。\n否：保留现有密码并跳过冲突行。\n取消：不导入任何内容。"},
  {L"Resolve password conflicts",L"解决密码冲突"},{L"Imported ",L"已导入 "},{L", updated ",L"，已更新 "},{L", skipped conflicts ",L"，已跳过冲突 "},{L". Remove the source CSV when finished.",L"。完成后请删除源 CSV。"},
  {L"Account granted to this client for its exact HTTPS origin.",L"已授权此客户端在完全匹配的 HTTPS 来源使用该账号。"},
  {L"Select a client and saved account.",L"请选择客户端和保存的账号。"},
  {L"Client account permission revoked.",L"已撤销客户端账号权限。"},{L"Account access blocked; the change could not be saved.",L"已阻止账号访问，但无法保存更改。"},
  {L"Remove this saved account from Xenon?",L"从 Xenon 删除此保存的账号？"},{L"Remove account",L"删除账号"},
  {L"Selected account allowed for this client, workspace, and exact origin.",L"已允许所选客户端在此工作区和完全匹配的来源使用所选账号。"},
  {L"Select an account, a paired client, and a shared workspace.",L"请选择账号、已配对的客户端和已共享的工作区。"},
  {L"Restored ",L"已恢复 "},{L" tabs with human control. Closed, private and protected tabs are excluded.",L" 个由您控制的标签页。已关闭、隐私和受保护的标签页不包含在内。"},
  {L"The operation failed. No secret details were logged.",L"操作失败。未记录任何秘密详情。"},
  {L"Pairing requests",L"配对请求"},{L"Approve only clients you recognize.",L"请仅批准您认识的客户端。"},
  {L"Approve",L"批准"},{L"Paired clients · connection and access",L"已配对客户端 · 连接和访问"},
  {L"Configure",L"配置"},{L"File resources",L"文件资源"},{L"Revoke / retry",L"撤销 / 重试"},{L"Stop all agents",L"停止所有代理"},
  {L"Connected agents in selected workspace",L"所选工作区中已连接的代理"},{L"Remove",L"删除"},
  {L"Private workspace",L"隐私工作区"},{L"Restore last session",L"恢复上次会话"},{L"Files",L"文件"},{L"Share read-only",L"以只读方式共享"},
  {L"Tabs in selected workspace",L"所选工作区中的标签页"},{L"Status",L"状态"},{L"Tab ID",L"标签页 ID"},
  {L"Take ownership",L"接管控制权"},{L"Give to agent",L"交给代理"},{L"Resume after login",L"登录后恢复"},
  {L"Accept dialog",L"接受对话框"},{L"Dismiss",L"取消"},
  {L"Saved accounts · shared encrypted vault",L"保存的账号 · 共享加密密码库"},
  {L"Import CSV",L"导入 CSV"},{L"Fill selected login tab",L"填写所选登录标签页"},
  {L"Selected client/workspace come from the other sections. Grants use exact HTTPS origins.",L"客户端和工作区需在其他页面选择。授权仅适用于完全匹配的 HTTPS 来源。"},
  {L"Grant to client",L"授权客户端"},{L"Revoke client grant",L"撤销客户端授权"},{L"Grant in workspace",L"在工作区中授权"},
  {L"HTTPS origin",L"HTTPS 来源"},{L"Account label",L"账号名称"},{L"Username",L"用户名"},{L"Password",L"密码"},
  {L"Save account",L"保存账号"},
  {L"Choose a section to manage clients, workspaces or saved passwords.",L"请选择一个页面来管理客户端、工作区或保存的密码。"},
  {L"Windows session locked. Agent control stopped.",L"Windows 会话已锁定。代理控制已停止。"},
  {L"Xenon could not initialize its protected local state.",L"Xenon 无法初始化受保护的本地状态。"},
  {L"Xenon requires the matching sandbox bootstrap executable.",L"Xenon 需要配套的沙盒启动程序。"},
  {L"Xenon setup is open. Finish or cancel setup before starting the browser.",L"Xenon 安装程序正在运行。启动浏览器前请完成或取消安装。"},
  {L"--broker-pipe requires a name beginning xenon- with at most 100 letters, digits, hyphens or underscores.",L"--broker-pipe 名称必须以 xenon- 开头，且不超过 100 个字母、数字、连字符或下划线。"},
  {L"--max-concurrent-workers requires an integer from 1 to 256.",L"--max-concurrent-workers 必须为 1 到 256 之间的整数。"},
  {L"Xenon closed, but setup could not start. Open Xenon and try the update again.",L"Xenon 已关闭，但无法启动安装程序。请打开 Xenon 后重新尝试更新。"},
  {L"Xenon update",L"Xenon 更新"},{L"Xenon could not start. Verify the installation and local data directory.",L"Xenon 无法启动。请检查安装和本地数据目录。"},
  {L"unknown origin",L"未知来源"},{L"Protected authentication. ",L"登录保护中。"},
  {L"Website ",L"网站"},{L" from ",L"，来源："},
  {L" in the selected tab. Review its message above, then Accept dialog or Dismiss. Prompt response goes to the website.",L"（所选标签页）。请查看上方消息，再选择接受对话框或取消。输入的回复将发送给网站。"},
  {L"alert",L"提示"},{L"confirm",L"确认对话框"},{L"prompt",L"输入对话框"},{L"beforeunload",L"离开页面确认"},
  {L"new",L"新增"},{L"created",L"已创建"},{L"existing",L"已存在"},{L"duplicate",L"重复"},{L"conflict",L"冲突"},{L"invalid",L"无效"},
  {L"(empty username)",L"（用户名为空）"},
  {L"An upload must belong to a workspace.",L"上传必须属于一个工作区。"},
  {L"Browser state and credential import files cannot be uploaded.",L"不能上传浏览器状态或凭据导入文件。"},
  {L"Revoke unused file grants before approving more.",L"批准更多文件前，请撤销不再使用的文件授权。"},
  {L"Choose an ordinary local file outside protected browser directories.",L"请选择受保护浏览器目录之外的普通本地文件。"},
  {L"A folder must belong to a workspace.",L"文件夹必须属于一个工作区。"},
  {L"Private browser directories cannot be granted.",L"不能授权私有浏览器目录。"},
  {L"Revoke an unused folder grant before approving another.",L"批准另一个文件夹前，请撤销不再使用的文件夹授权。"},
  {L"Choose an ordinary local folder outside protected browser directories.",L"请选择受保护浏览器目录之外的普通本地文件夹。"},
  {L"Access is revoked for this session, but the persisted policy could not be updated. Close Xenon before restarting.",L"本次会话已撤销访问，但无法更新保存的策略。请先关闭 Xenon 再重启。"},
  {L"The CSV import is limited to 16 MiB.",L"CSV 导入大小上限为 16 MiB。"},
  {L"The selected file could not be read.",L"无法读取所选文件。"},
  {L"The selected file changed while being read.",L"所选文件在读取期间发生了更改。"},
  {L"Use a UTF-8 browser password export.",L"请使用 UTF-8 编码的浏览器密码导出文件。"},
  {L"The password CSV is malformed or unreadable. No credentials were imported.",L"密码 CSV 格式有误或无法读取。未导入任何凭据。"},
  {L"The password CSV has no header.",L"密码 CSV 没有表头。"},
  {L"The CSV contains duplicate credential columns.",L"CSV 包含重复的凭据列。"},
  {L"Expected URL, username and password columns from a browser export.",L"需要浏览器导出文件中的 URL、用户名和密码列。"},
  {L"A different password is already saved for this account; confirm an update in Xenon.",L"此账号已保存了不同的密码；请在 Xenon 中确认更新。"},
  {L"The account is unavailable for this origin.",L"此来源无法使用该账号。"},
  {L"Unlock Xenon before accessing saved accounts.",L"访问保存的账号前请先解锁 Xenon。"},
  {L"Saved accounts require an exact HTTPS origin.",L"保存的账号需要完全匹配的 HTTPS 来源。"},
  {L"Saved account metadata is unavailable.",L"保存的账号信息不可用。"},
  {L"Only valid HTTPS website logins can be saved.",L"仅可保存有效的 HTTPS 网站登录信息。"},
  {L"The credential contains unsupported or oversized fields.",L"凭据包含不支持或过长的字段。"},
  {L"Unlock Xenon before saving an account.",L"保存账号前请先解锁 Xenon。"},
  {L"The credential could not be saved.",L"无法保存凭据。"},
  {L"Unlock Xenon before removing an account.",L"删除账号前请先解锁 Xenon。"},
  {L"The account could not be removed.",L"无法删除账号。"},
  {L"Use a short account label without control characters.",L"请使用不含控制字符的简短账号名称。"},
  {L"The save request expired or is no longer available.",L"保存请求已过期或不再可用。"},
  {L"The saved account changed after this request. Log in again before confirming an update.",L"保存的账号在此次请求后发生了更改。确认更新前请重新登录。"},
  {L"The credential could not be saved. Log in again to create a new save request.",L"无法保存凭据。请重新登录以创建新的保存请求。"},
  {L"Unlock Xenon before previewing accounts.",L"预览账号前请先解锁 Xenon。"},
  {L"The credential import preview is unavailable. Nothing was imported.",L"凭据导入预览不可用。未导入任何内容。"},
  {L"The CSV changed after preview. Preview the file again before importing.",L"CSV 在预览后发生了更改。导入前请重新预览文件。"},
  {L"The import could not be verified.",L"无法验证导入。"},
  {L"Unlock Xenon before importing accounts.",L"导入账号前请先解锁 Xenon。"},
  {L"The import could not be completed. No credentials were imported.",L"无法完成导入。未导入任何凭据。"},
  {L"Workspace could not be saved",L"无法保存工作区"},
  {L"Workspace cannot be opened",L"无法打开工作区"},
  {L"Workspace names must contain at most 80 characters and no control characters",L"工作区名称最多可包含 80 个字符，且不能含有控制字符"},
  {L"Workspace was not removed because its recovery record could not be saved. Retry after storage is available.",L"无法保存恢复记录，因此工作区未被删除。存储可用后请重试。"},
  {L"Workspace access is revoked and removal is saved, but browser closure did not finish. Retry removal or restart the browser to complete cleanup.",L"工作区访问已撤销，删除已保存，但浏览器关闭尚未完成。请重试删除或重启浏览器以完成清理。"},
  {L"Workspace removal is saved and will finish during the next browser start",L"工作区删除已保存，将在下次启动浏览器时完成"},
  {L"The update request timed out. Try again later.",L"更新请求超时。请稍后重试。"},
  {L"The native HTTPS updater is unavailable.",L"原生 HTTPS 更新功能不可用。"},
  {L"Secure update transport is unavailable.",L"安全更新传输不可用。"},
  {L"Cannot connect to the update service.",L"无法连接更新服务。"},
  {L"The secure update request failed. Check the network and try again.",L"安全更新请求失败。请检查网络后重试。"},
  {L"The update service did not return a valid response.",L"更新服务未返回有效响应。"},
  {L"The update service is rate limited or unavailable. Try again later.",L"更新服务受到请求频率限制或暂时不可用。请稍后重试。"},
  {L"The update service returned an unsuccessful response.",L"更新服务返回了失败响应。"},
  {L"The update download was interrupted. Try again later.",L"更新下载中断。请稍后重试。"},
  {L"The update download was incomplete.",L"更新下载不完整。"},
  {L"The update request could not complete.",L"无法完成更新请求。"},
  {L"The update response exceeded its permitted size.",L"更新响应超过允许的大小。"},
  {L"The update response size does not match its metadata.",L"更新响应大小与元数据不符。"},
  {L"The staged update size does not match its release.",L"暂存更新的大小与发布版本不符。"},
  {L"The staged update failed SHA-256 verification.",L"暂存更新未通过 SHA-256 验证。"},
  {L"The update service returned invalid release metadata.",L"更新服务返回了无效的发布元数据。"},
  {L"Update release metadata is invalid.",L"更新发布元数据无效。"},
  {L"Cannot create private update storage.",L"无法创建私有更新存储。"},
  {L"Cannot create the private update file.",L"无法创建私有更新文件。"},
  {L"Cannot write the update download.",L"无法写入下载的更新。"},
  {L"Cannot finish writing the update download.",L"无法完成更新文件写入。"},
  {L"Cannot publish the verified update file.",L"无法保存已验证的更新文件。"},
  {L"The verified installer could not start. Windows may have blocked this unsigned file.",L"无法启动已验证的安装程序。Windows 可能阻止了此未签名文件。"}
};
// Call only for Xenon-owned UI copy, never website content, names, IDs or commands.
inline const wchar_t* tr(const wchar_t* english) {
  if(language==Language::simplified_chinese)
    for(const auto& entry:translations)if(std::wstring_view(english)==entry.english)return entry.chinese;
  return english;
}
// Win32 filters contain embedded NULs and are not ordinary translation keys.
inline const wchar_t* file_filter(bool csv) {
  if(language==Language::simplified_chinese)return csv?L"密码 CSV\0*.csv\0所有文件\0*.*\0":L"文件\0*.*\0";
  return csv?L"Password CSV\0*.csv\0All files\0*.*\0":L"Files\0*.*\0";
}
inline const wchar_t* pdf_filter() {return language==Language::simplified_chinese?L"PDF 文档\0*.pdf\0":L"PDF document\0*.pdf\0";}
}
